name: Payments Microservice CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "payments/**"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean project
      working-directory: ./payments
      run: npm ci
    - name: Build
      working-directory: ./payments
      run: npm run build --if-present
    - name: Test
      working-directory: ./payments
      run: npm run test:ci
